[tool.poetry]
name = "mlsp-covid"
version = "0.1.0"
description = ""
authors = ["TheCarmelGuy <komelm13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.6.0"
click = "^8.1.8"
numpy = "^2.2.4"
lightning = "^2.5.1"
pillow = "^11.1.0"
scipy = "^1.15.2"
pandas = "^2.2.3"
scikit-image = "^0.25.2"
torchvision = "^0.21.0"
matplotlib = "^3.10.1"
scikit-learn = "^1.6.1"
tensorboard = "^2.19.0"
pyqt5 = "^5.15.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
